const axios = require('axios');

async function checkChapterDetails(chapterId) {
  const API_BASE_URL = 'https://api.mangadex.org';
  const AUTH_TOKEN = 'eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJHSHg0Qmk2THhvdVRGLWZuQmg0WXhMbUtUbGZzT2tmTm9fQ05yT1pMZHNrIn0.eyJleHAiOjE3MjM0MjQ2ODEsImlhdCI6MTcyMzQyMzc4MSwianRpIjoiYWViY2FhMDAtZmJiNy00MGMyLWIzZGItYjczNDljMjc3MDY2IiwiaXNzIjoiaHR0cHM6Ly9hdXRoLm1hbmdhZGV4Lm9yZy9yZWFsbXMvbWFuZ2FkZXgiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiNmY3NjRiZWYtN2QxOS00ZDEwLThlZjEtMTE3NzdjYWY5MDgyIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoicGVyc29uYWwtY2xpZW50LTZmNzY0YmVmLTdkMTktNGQxMC04ZWYxLTExNzc3Y2FmOTA4Mi00NzNhMDVkNCIsInNlc3Npb25fc3RhdGUiOiJhYzk3ZjA5OC1lYTkyLTRjMDktOWJhMy1mNDU2OTQ5NTEwYTUiLCJhY3IiOiIxIiwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoiZ3JvdXBzIGVtYWlsIHByb2ZpbGUiLCJzaWQiOiJhYzk3ZjA5OC1lYTkyLTRjMDktOWJhMy1mNDU2OTQ5NTEwYTUiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicm9sZXMiOlsiUk9MRV9VU0VSIiwib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiIsImRlZmF1bHQtcm9sZXMtbWFuZ2FkZXgiXSwiZ3JvdXBzIjpbIkdST1VQX1VTRVIiXSwiY2xpZW50X3R5cGUiOiJwZXJzb25hbCIsIm9pZCI6IjZmNzY0YmVmLTdkMTktNGQxMC04ZWYxLTExNzc3Y2FmOTA4MiIsInByZWZlcnJlZF91c2VybmFtZSI6Imh1YWJpIiwiZW1haWwiOiJtYXJpbmNoZW5nZ0BvdXRsb29rLmNvbSJ9.lbxIBms42kN6_CzdlMuvGfuxttdGHK_Z-zmFLVQ2krn0a7xQ13GmxnXTZdQFUoEfItxbL-mlQnC5AVsWP4kmZEkj4WWmD5-KxbPQMqc3WUcQPNMLM6NGb0Tunk9-vO9C-Yur-Y6YovO_HBgaZXRfZ5W_q6NK_YrgjeSHQ677f_wTh3QnAxZRumKoJzkDNnMzbswlL3fDKdALdT1ERYoDydEjD_adJ8UqrrjsZuJVq9hBf59BIQLqKTB9G_058mRBtdnz5xIRdMbVarRSQleUaMfFxZ5qHonqJr5Oc1RwRhr-z-uo6K6fNk_026U0bA50zdduBd2OBbC7BQdxhbdFVQ'; // Asegúrate de usar un token válido

  try {
    const response = await axios.get(`${API_BASE_URL}/chapter/${chapterId}`, {
      headers: {
        Authorization: `Bearer ${AUTH_TOKEN}`
      }
    });
    console.log('Chapter details:', response.data);
  } catch (error) {
    console.error('Error fetching chapter details:', error.response ? error.response.data : error.message);
  }
}

checkChapterDetails('02187804-db81-443e-aa18-8946a05cc0e8');
